### ISSUE TITLE
Hours section of Little Steve post shows incorrect number

### ISSUE THREAD

**Issue by jatmdm** [niceprogramming/DestinyBot#3]
First occurrence was 12/7/18, however it seems like it only affected Oxygen not Included.
Second occurrence was 12/8/18, but that affected all games listed.
![2018-12-08 23_14_21- destinyhub - discord](https://user-images.githubusercontent.com/3706276/49693379-10502780-fb3f-11e8-82a0-f274c40f6140.png)
![2018-12-08 23_14_32- destinyhub - discord](https://user-images.githubusercontent.com/3706276/49693380-10502780-fb3f-11e8-9f44-3c72cec44842.png)

**Comment by niceprogramming** [comment]
This should be fixed now. Let it be known through all the lands that the Twitch API is terrible.
